version: "3"
services:
  api-service:
    build: .
    container_name: flask-memchached
    ports:
      - "80:5000"
    environment:
      CACHE_HOST: "$CACHE_HOST"
      CACHE_PORT: "$CACHE_PORT"
    depends_on:
      - cache
  cache:
    image: memcached:latest
    container_name: cache-memchached
    entrypoint:
      - memcached
      - -m 64
    ports:
      - "11211:11211"
    expose:
      - "11211"